### PR TITLE
Support binary logical attributes

### PR DESCRIPTION
**Pull request by Pessimistress**
For #3758, implements the RFC in #3884 

#### Change List
- Drops support for external attributes in top-level props
- Add `attribute.setBinaryValue`, support auto-packed attributes
- Unit tests

#### TODO (follow-up PRs)
- `PathLayer`
- `SolidPolygonLayer`

### CODE REVIEW

**Comment by Pessimistress** [comment]
@tsherif What do you think of:

- revert `setVirtualBuffer` back to `setExternalBuffer` (both Buffer instance and typed arrays are supported in this path)
- rename `setLogicalBuffer` to `setPackedDataSource` (only typed arrays are supported)

**Comment by ibgreen** [comment]
Doing to a deep review on this now, will take some time, my initial thoughts are just as @tsherif says that we need to sort out the naming here. I will review carefully and also think about this from the perspective of the `GPUTable` proposal and see if we can align with that.

PS - I am 100% onboard with dropping support for external buffers in props, but can we still have a check for those props and just issue errors/warnings if we see them? These things tend to be very tricky for application upgraders to figure out, they are sometimes updating the deck.gl version in an app they haven't touched in over a year and now it will fail silently or at least mysteriously due to some obscure prop no longer being read...

**Comment by tsherif** [comment]
Maybe `setPackedDataSource` -> `setPackedArray`? Otherwise, LGTM.

**Comment by Pessimistress** [comment]
> `setPackedArray`

I don't think this name offers sufficient clarity - we will still need to explain what `packed` means and how it relates to the value of the attribute.

I kind of like the term "logical" here. We also have `logicalType` in `Attribute` that may be `GL.DOUBLE`. If the main concern is `Buffer` vs `Array` maybe we can use `setLogicalValue`?

**Comment by tsherif** [comment]
The term "logical" doesn't really say anything to me about the data. Is this usage common? I might just be missing the reference.

Either way, I'm ok with it as long as the definitions are documented.

**Comment by Pessimistress** [comment]
@ibgreen Merging for now. If you have more comments I'll address in follow up PRs.

**Pull request merged**
