### PR TITLE
Layer.parameters: Update docs and forward prop in GeojsonLayer

### PR DESCRIPTION
**Pull request by ibgreen**

### CODE REVIEW

**Comment by ibgreen** [comment]
See #873

**Comment by ibgreen** [comment]
@georgios-uber

**Comment by georgios-uber** [comment]
Great

**Comment by georgios-uber** [comment]
Great

**Comment by 1chandu** [comment]
@ibgreen looks good, thanks for taking care of this.

One thing I notices when looking into layer.js , `this.props` is never used, but then I saw , `layer.props.parameters` are passed back to `drawLayer` method, which was bit confusing. May be we should only pass any extra `parameters` to this method and then merge them with this.parameters.

**Pull request merged**
