### PR TITLE
Cleanup dist files and gitignore

### PR DESCRIPTION
**Pull request by Apercu**
Reorganize `.gitignore` and remove legacy references, remove `dist-demo` folder from git.

### CODE REVIEW

**Comment by ibgreen** [comment]
About the dist-demo folder. I believe we use `git subtree` to publish it to `gh-pages`. Would that still work if we remove it from git on master? @Pessimistress @manassra

**Comment by Apercu** [comment]
Not familiar with subtrees, but I don't seem to grasp why it should be tracked on `master` when it's needed only in `gh-pages`, but untracked there.

**Comment by ibgreen** [comment]
> I don't seem to grasp why it should be tracked on master when it's needed only in gh-pages, but untracked there.
Good question. I am open to improvements in the way we push to `gh-pages`, our current method is rather fragile.

**Comment by Apercu** [comment]
@ibgreen Any update on this one? Don't see the problem with ignoring it on `master`, since we would only have to copy its content in the root of `gh-pages` once we want to update it.

**Comment by ibgreen** [comment]
> Any update on this one? 

@apercu I completely agree that it would be much preferable to not check in the demo-dist directory on master.

>Don't see the problem with ignoring it on `master`, since we would only have to copy its content in the root of `gh-pages` once we want to update it.

I would just like to understand how we would do the copy of `demo-dist` from `master` to `gh-pages`? We currently use `git-subtree`. Can `git-subtree` access files we have not committed? If it can, then go ahead and remove `demo-dist`.

Finally, note that this work should be done on `dev` instead of `master`. `demo` has moved to a new directory there with its own package.json, so it may be possible to arrange things in a better way now.

**Comment by ibgreen** [comment]
Closing as further work should be done on dev.

**Pull request closed without merging**
