### PR TITLE
Update token and id for Melbourne 3d tiles

### PR DESCRIPTION
**Pull request by xintongxia**
## Background
- use UberVisTeam Token

#### Change List
- 3d-tiles example

### CODE REVIEW

**Comment by mayteio** [comment]
Hey! I'm from the team (GIS Smart City Office Melbourne) responsible for managing this point cloud and just wanted to say - thanks for using it. Did you pick it up from our Open Data platform?

**Comment by xintongxia** [comment]
@mayteio 

Data is from cesium ion server.

**Comment by mayteio** [comment]
I see - I just meant the source of the data - https://data.melbourne.vic.gov.au/Property-Planning/City-of-Melbourne-3D-Point-Cloud-2018/2dqj-9ydd

**Comment by ibgreen** [comment]
> - thanks for using it. 

Thanks for letting us use it, it is an awesome cloud, we really love that it is colored.

> Did you pick it up from our Open Data platform?

@OmarShehata from Cesium may know more about how this cloud was selected.

> We're potentially looking at 2cm a point cloud next. Will deck.gl be able to handle it?

Yes it should, as long as it is properly tiled and served. Do you have a sense for how many points it will be? (current cloud is 355 million points).

**Comment by mayteio** [comment]
It's open data, that's what it's for! Thanks for bestowing deck.gl on the world, we regularly use it for [community engagement](https://sunlight-to-parks.netlify.com) and making our open data [accessible to the public](https://city-dna-2019.netlify.com). We've even used it to project onto a [4msq 3D printed model of our city](https://www.linkedin.com/posts/harleytalexander_smartcity-activity-6536184587570282496-qXc3) - the trips layer looked AMAZING running down the streets. It was the main feature at [Melbourne Knowledge Week](https://www.linkedin.com/posts/harleytalexander_melbourne-city-dna-exhibition-at-melbourne-activity-6569005010229829632-pSHL). Incredible tool. 

I believe it'll be in the range of a billion points. It's out to tender at the moment - will keep you in the loop.

**Comment by OmarShehata** [comment]
Hey @mayteio, 

I want to echo my thanks as well for your work curating and making this awesome dataset accessible! We did indeed download the source that City of Melbourne website. The data are tiled as 3D Tiles so that clients like Deck.gl can stream it in, so it should handle 2cm resolution pretty well (we've had showcases [with sub-centimeter accuracy](https://cesium.com/blog/2018/02/05/historic-pharsalia-cabin-point-cloud/)).

**Pull request merged**
