### PR TITLE
Temp fix for path-outline-layer issue

### PR DESCRIPTION
**Pull request by georgios-uber**

### CODE REVIEW

**Comment by jianhuang01** [comment]
This fix will introduce new issues, recommend not to check in.
For example with this data     path: [
      [8584.484798702775, 6742.5945553739575],
      [2908.5139320879325, 429.453672569738],
      [8000.484798702775, 6742.5945553739575],
      [8000.485798702775, 6742.5945553739575],
      [9100.486798702775, 7742.5945553739575]
    ]
sharp_end2

**Comment by georgios-uber** [comment]
@jianhuang01 What is the issue?

**Comment by jianhuang01** [comment]
@georgios-uber there is an extra segment rendering on the up-right area.

**Comment by georgios-uber** [comment]
@jianhuang01 That's 5 total, seems correct.

**Comment by georgios-uber** [comment]
@jianhuang01 Deleting this merge in favor of https://github.com/uber/deck.gl/pull/1200

**Pull request closed without merging**
