### PR TITLE
Upgrade luma.gl to v5.3.1

### PR DESCRIPTION
**Pull request by EllaZhao**
Upgrade luma.gl to v5.3.1 for including the fix https://github.com/uber/luma.gl/pull/760

### CODE REVIEW

**Comment by EllaZhao** [comment]
Is this pull request ready to merge? Thanks in advance.

**Comment by LitoMore** [comment]
Any update on this?

**Comment by 1chandu** [comment]
Working on publishing a new path with this change.

**Comment by 1chandu** [comment]
@LitoMore @EllaZhao , deck.gl v5.3.5 published.

**Pull request merged**
