### PR TITLE
SegmentLayer - a Path layer that uses a shadow buffer to create outlines between paths at different heights

### PR DESCRIPTION
**Pull request by ibgreen**
screen shot 2017-09-26 at 7 21 39 pm

### CODE REVIEW

**Comment by ibgreen** [comment]
@1chandu - `segment-layer.js` in this PR is where the framebuffer fixes you are working on will be used.

**Comment by gnavvy** [comment]
Not in this PR but would it be feasible to merge this layer back to the path layer, as from the visuals the segment layer looks a path layer with enhanced visual effects? Or are targeting at making such effects applicable to all existing primitive layers like the filter effects in SVG?

**Comment by shaojingli** [comment]
This is some great work. One thing that we could consider here is that if we'd like to rewrite the path layer in the future (both 32-bit and 64-bit). How easy is it to port it to the new path layer?

**Comment by ibgreen** [comment]
> This is some great work. 

It is a port of @george-uber's THREE.js implementation, he should have the credit.

> One thing that we could consider here is that if we'd like to rewrite the path layer in the future (both 32-bit and 64-bit). How easy is it to port it to the new path layer?

> Not in this PR but would it be feasible to merge this layer back to the path layer, as from the visuals the segment layer looks a path layer with enhanced visual effects? Or are targeting at making such effects applicable to all existing primitive layers like the filter effects in SVG?

Long term I would very much like to make this into a generic feature for all layers. For now you can see in the PR that the outline shadowmap piece is already organized as a reusable shader module, so that is a start.

But there are a number of issues remaining:
- we are still flushing out some Framebuffer handling bugs in luma.gl, 
- there are problems with current implementation in perspective mode (only works with pitch=0), that is why I am keeping this as a sample layer for now.

Note that shader module injection system improvements could making adding this to other layers much easier. Have started to put down my ideas, I am afraid it is [Yet Another Half-Finished RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/vNext/shader-module-injection-rfc.md).

**Pull request merged**
