### PR TITLE
initial pass at deriving projectionMatrix

### PR DESCRIPTION
**Pull request by chrisirhc**
First pass at addressing https://github.com/uber/deck.gl/commit/0c6b550ac01f8761418bb0c898bc9dead86ce29b#commitcomment-17741074.

There are some things I'm unsure about for this change:
- Default values for mapViewState aren't obvious and come from mapbox-gl
- Adding mapbox-gl as a dependency  

I looked into https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/transform.js and it looks like there's quite a bit of logic for calculating the projection matrix that relies on default values that are set up in the `transform.js` . For example, `maxZoom` comes from mapbox-gl's Map .

What's left:
- [x] Remove dependency on `mapbox-gl`

### CODE REVIEW

**Comment by ibgreen** [comment]
@chrisirhc You certainly did your homework, this would probably work and is a slight improvement over the current situation.

However, I think your initial suggestion (your comment on my change) was correct, deck.gl should not have any dependencies on mapbox or react-map-gl. 
- The only coupling is that deck.gl understands the same lat/lon/zoom/pitch/bearing props as react-map-gl which results in perfect overlay sync.
- Other map components could implement those props as well, and deck.gl would work with them out of the box (and without pulling in the big `react-map-gl` dependency).

The way this is currently solved on master is through small a math helper module (`viewport-mercator-project`) that enables projection of (lat/lon/zoom) to x,y points in a way that is compatible with mapbox. I think the right solution here is to either add `pitch/bearing` to that module or create another helper module that does this.

And yes, as you pointed out, this means duplicating the math in mapbox-gl-js/.../transform.js.

This is the main remaining blocker for the beta, once this is done I think we can end the `1.0.0-beta` series and officially merge dev to master and publish `react-map-gl@1.0.0`. This task is pretty high on my priority list, but happy to support you on this if you want to make an attempt.

**Comment by chrisirhc** [comment]
Sounds good, I'll look into that helper module and see what I can do there.

**Comment by ibgreen** [comment]
I'd start by `npm i --save gl-matrix` and then perform the same matrix calculations that mapbox `Transform` class does in `_calcProjMatrix` (very end of `transform.js` if I remember correctly).

**Comment by chrisirhc** [comment]
@ibgreen I've based this on an older version because I can't seem to get tests running on the latest dev.

```
> deck.gl@3.0.0-beta10 test-headless /Users/chris/Documents/code/deck.gl
> babel-node --only=test,src test/headless.js | faucet

not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
```

**Comment by chrisirhc** [comment]
Updated PR to clean up surface area.

**Comment by ibgreen** [comment]
@chrisirhc 
- Merged a modified version of this branch and published 3.0.0-beta12.
- Will polish a bit more and then move to react-map-gl, but for now the code can stay in deck.gl, it is easier to iterate in this repo.
- Thanks a ton for the help!

**Pull request closed without merging**
