### PR TITLE
Experimental Floating Solid Polygon Layer

### PR DESCRIPTION
**Pull request by chrisgervang**
For #1525

### CODE REVIEW

**Comment by chrisgervang** [comment]
I'm not sure why, but locally 52 tests fail. The tests don't seem to be related to my changes.. am I missing something?

**Comment by jianhuang01** [comment]
@chrisgervang we are fixing the problem on master, there is a bug in recent luma.gl alpha releases, hardcode luma.gl version to "5.2.0-alpha.3" can resolve the test issue.

**Comment by jianhuang01** [comment]
@chrisgervang The test should be OK now, pull the latest code, please. Thanks for reporting the issue.

**Comment by Pessimistress** [comment]
@chrisgervang This PR is getting stale and probably too hard to rebase. There were two features discussed in the original issue:

- setting the base `z` per vertex, which is now supported by the 6.x releases;
- setting extrusion per vertex, which as far as I can tell is not addressed in this PR. We will continue to track the request.

**Pull request closed without merging**
