### PR TITLE
Transpile demo workers to es5

### PR DESCRIPTION
**Pull request by Pessimistress**
https://github.com/uber/deck.gl/issues/691

### CODE REVIEW

**Comment by shaojingli** [comment]
This will also solve #618 right?

**Comment by kktam** [comment]
There seemed to be some problem with trans-piled output.

for example in the [Arc Example](https://github.com/uber/deck.gl/tree/master/examples/arc), the error is located at bundle.js 

```
line 74974
var pageLoadPromise = isBrowser ? new Promise(function (resolve, reject) {
  window.onload = function () {
    isPageLoaded = true;
    resolve(document);
  };
}) : Promise.resolve({});
```

```
SCRIPT5009: 'Promise' is undefined
File: bundle.js, Line: 74974, Column: 1
```

This error is captured in IE 11 Version 11.0.9600.18617

**Comment by ibgreen** [comment]
> 'Promise' is undefined

@kktam  Thanks for reporting this. This should be solvable by the application by importing a polyfill like `babel-polyfill` or similar.

In the example folder.
`yarn add babel-polyfill` or 
`npm install babel-polyfill`

In `app.js`, add
```
require('babel-polyfill`);
```
before other code

While we do want to support IE11, I think we should handle this through documentation (i.e. have a section about how to add the polyfill), rather than make all apps pay the cost of a polyfill when all modern browsers already define `Promise` by default.

@shaojingli @Pessimistress

**Comment by ibgreen** [comment]
Opened #845

**Pull request merged**
