### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by balthazar**
Throwing this PR so people can give feedback. Prettier is already enabled by default on the new uber eslint configs, so it's only a matter of time that we switch to it.

I've decided to leave coma dangles alone for now in order to see if people have strong opinions against them, but note this appear to be the new Uber normal.

Will fix merge conflicts after validation.

### CODE REVIEW

**Comment by balthazar** [comment]
@ibgreen @1chandu The build is segfaulting. Should we merge anyway?

**Comment by ibgreen** [comment]
Yes, Travis has issues - we either need to get the buildkite integration online, or fix Travis. 

But you actually got one clean run, so that is good enough to merge

**Comment by ibgreen** [comment]
Alea iacta est... 90K lines...

Ye who have PRs that still need to be rebased, abandon all hope :)

**Comment by balthazar** [comment]
@ibgreen if you manage to run the prettier on the code to be rebased, you might avoid some pain

**Comment by ibgreen** [comment]
@balthazar Yes, very good point!

**Pull request merged**
