### PR TITLE
【Feature】Add a new layer in experimental-layers

### PR DESCRIPTION
**Pull request by DLCJianyf**
#### Background
  It's a need for me to create layer both has border and fill. In the same time the point geomtry need use pixel as unit.

#### Change List
-The layer can also have border and fill color
-Point size using pixels as units

### test
test in examples(capture in my browser)

tim 20180723154631

### CODE REVIEW

**Comment by 1chandu** [comment]
Thanks for the PR, can you sign the CLA.
Also , is it possible to add a new prop to existing `ScatterplotLayer` and control all the JS and Shader code under it, this new prop can be experimental.

**Comment by DLCJianyf** [comment]
ok, i will do that , but there are some mistakes in my account. i have signed the CLA. but it still in waiting.  How can i cancel this commit. i want use other account to commit, that account signed the CLA

**Comment by ibgreen** [comment]
>  How can i cancel this commit. i want use other account to commit, that account signed the CLA

In that case, just open another PR from the other account. I can close this PR once you do.

**Comment by DLCJianyf** [comment]
ok

**Comment by DLCJianyf** [comment]
i have commit it use annother account. and all checked

**Pull request closed without merging**
