### PR TITLE
Remove references to non-scoped deck.gl module

### PR DESCRIPTION
**Pull request by ibgreen**
# For #2551 

#### Change List
- docs and examples

### CODE REVIEW

**Comment by Pessimistress** [comment]
I agree that some generic code samples should be importing from sub modules.

However, the code samples that are in React have no reason to not use `deck.gl`. Our get started guide and main examples all specify the single dependency `deck.gl`. Importing extraneous packages such as `@deck.gl/react` is bad practice. In fact, our internal monorepo has lint rules against it.

**Comment by ibgreen** [comment]
agree that some generic code samples should be importing from sub modules.

> However, the code samples that are in React have no reason to not use deck.gl. Our get started guide and main examples all specify the single dependency deck.gl. 

I guess this PR is my take on how we should deal with the issues raised in #2519, and probably highlights a difference of view. 

Obviously, I see the main `deck.gl` package as a legacy package that was kept to avoid breaking old code, but that should be phased out. I don't see a particular reason to have a special convenience package that favors react over other implementations.

> Importing extraneous packages such as @deck.gl/react is bad practice. In fact, our internal monorepo has lint rules against it.

I am not sure that I understand this point. In what sense is this an extraneous package if the legacy deck.gl module is no longer installed? How would the monorepo even be able to detect that?

**Comment by Pessimistress** [comment]
It's a different topic then, whether we should deprecate the master package. Shall we leave that controversy out of this PR and move the discussion to the issue thread?

**Comment by ibgreen** [comment]
> Shall we leave that controversy out of this PR and move the discussion to the issue thread?

Sure. This PR just "happened" as I was following another trail, and I decided to put it up to see where things stood.

**Pull request closed without merging**
