### PR TITLE
Controller prop for smooth zoom in/out 

### PR DESCRIPTION
**Pull request by Lowhearth**
Hello,
thanks again for this amazing library, I'm learning a lot just by browsing the source code and experimenting.

I had to implement the feature of smooth zooming and came up with this solution, a zoomTransition Controller option that will set the transitionDuration for the animation. #2941 

Let me know what you think and how can I improve it  

  - [X] Add label and assign to milestone 
  - [X] Coding
  - [X] Test
  - [ ] Doc update
  - [ ] What’s new update 

#### Change List
- Added a prop to the Controller class

### CODE REVIEW

**Comment by Pessimistress** [comment]
You can achieve this by extending the default `MapController` class:

```js
import DeckGL, {MapController} from 'deck.gl'

class MyController extends MapController {
  _getTransitionProps() {
    return {transitionDuration: 0};
  }
}

<DeckGL ... controller={MyController} />

```

**Comment by Lowhearth** [comment]
Definitely taking this approach if we decide that the feature is not worthy to be included in the controller class.
¿ Wouldn't it be good to have this built in feature ?

**Comment by Pessimistress** [comment]
There are a lot of hard-coded behaviors in the controller class, e.g. transition duration/interpolator, increment for keyboard navigation, etc. I think it's a great suggestion that we should expose them as options. I would avoid making individual additions like this and come up with a comprehensive list of options.

**Comment by Lowhearth** [comment]
I couldn't agree more

**Pull request closed without merging**
