### PR TITLE
Simple webpack and browserify exhibits

### LINKED ISSUE #247: Add basic webpack and browserify example
We need to have a common place to demonstrate basic usage of deck.gl using browserify and webpack, and be able to point directly at the code.

### PR DESCRIPTION
**Pull request by Apercu**
This introduce a simple and unified usage of `deck.gl` along with `webpack` and `browserify`, so people have a good base to work on with either tool, trimmed from fancy stuff.

Closes #247.

### CODE REVIEW

**Comment by Apercu** [comment]
https://www.traviscistatus.com/

**Comment by ibgreen** [comment]
>  https://www.traviscistatus.com/
OK, I was afraid that it was our move to Node 6/7 that caused the increase in CI time.

**Comment by Apercu** [comment]
Nope, a few builds already passed after this change. Should I merge? Dunno how long it's gonna last

**Comment by Apercu** [comment]
Thanks for contradicting me @travis-ci.

**Pull request merged**
